### ISSUE TITLE
Including subdirectories

### ISSUE THREAD

**Issue by filipecfv** [namilus/denote-menu#10]
Hi. I am enjoying this package; it is a great idea, but it takes all the notes from the subfolders and gathers them all into one single page. 
 
Although surely the most recommended approach is to store all one's notes into a single folder, Denote allows one to organize them alternatively by creating subfolders that are visible via dired-mode view. 
  
That said, is there a way to see the subdirectories in the denote-directory via denote-menu view?

I appreciate any response.

**Comment by namilus** [comment]
Hi @filipecfv,

As of right now, there isn't any way to do that. This could be something to include in a new release of denote-menu.

**Comment by namilus** [comment]
To correct my previous comment, looks like denote menu does show files within subdirectories of the `denote-directory`. Having tested this locally (denote-menu v1.1.1 and denote v1.2.0), I will close this issue

**Comment by filipecfv** [comment]
I does show files within subdirectories, but it doesn't show the subdirectories themselves. It rather takes all files, from the main directory and the subdirectories, and gathers them all in one place, while in vanilla Denote, via dired-mode, one is able to see all subdirectories within the denote-directory and also be able to enter the subdirectory and see only those notes contained in the subdirectory.
