### ISSUE TITLE
Ttile not displayed correctly

### ISSUE THREAD

**Issue by julian-hoch** [namilus/denote-menu#16]
The readme states that denote-menu supposedly removes the "clutter of hyphens and underscores". In my case, this does not seem to work - the "Title" column is basically just the file name without the tags, including the hypens and file ending.
Not sure if this is a known issue (does not seem like it), but if it is, I would be grateful for any ideas on how to fix this.

**Comment by namilus** [comment]
Hi Julian,

Which version of Denote are you using? Prot recently released v3.0.0 and that has broken a few things. I'm currently working on fixing this.

Thanks

**Comment by julian-hoch** [comment]
Hi,
not quite sure, the documentation seems to indicate 3.0.0 but not 100% certain if that is reliable.
In any case, now I have bigger problems: I now get "symbol's function definition is void: denote-directory-files-matching-regexp"
Potentially related to the version upgrade?

**Comment by namilus** [comment]
Hi Julian,
Please pull the most recent commit. I've addressed these issues. Let me know if all works well and I'll prepare a new release.

Thanks :smile:

**Comment by julian-hoch** [comment]
Yeah looks good! Everything is working again, and titles are displaying correctly!

**Comment by namilus** [comment]
Closing this issue. A new build of denote-menu has been triggered for ELPA.
