### ISSUE TITLE
denote-menu-update-entries calls a deprecated function denote-directory-files-matching-regexp

### ISSUE THREAD

**Issue by mlmbl** [namilus/denote-menu#17]
I install and use `denote.el` and `denote-menu` from MELPA. 

For the past few days, I've been encountering an error while executing `list-denotes` (i.e., `denote-menu-list-notes`). The error specifically states, "Symbol's function definition is void: denote-directory-files-matching-regexp."

Upon reviewing the denote.el website, I discovered that `denote-directory-files-matching-regexp` has been deprecated since version 2.2.0, and the `denote-directory-files` subsumes it.

In `denote-menu.el`, `denote-directory-files-matching-regexp` is called in `denote-menu-update-entries` on line 134.

When I just replaced the call to `denote-directory-files-matching-regexp` with `denote-directory-files`, it seems the function is operating as before.

**Comment by namilus** [comment]
Hi,
This has been fixed in the most recent commit. Please pull it and have a go. If all is well i'll prepare a new elpa release.

Thanks :smile:

**Comment by anonimno1** [comment]
Hi @namilus 

I just did the change localy and it worked. Please push to ELPA.

Thanks!

**Comment by namilus** [comment]
Closing the issue. A new build has been triggered for ELPA. Thank you everyone for helping sort this out
