### ISSUE TITLE
Suggestion for doc strings

### ISSUE THREAD

**Issue by protesilaos** [namilus/denote-menu#2]
Hello @namilus and congratulations on your first package!

Here I have some suggestions for the language used in the doc strings: https://github.com/protesilaos/denote-menu/commit/8a490728de763c5b5a2a9c905b92d5eda5203755

I am not sending it as a pull request, since this is just for your information.  You are welcome to adapt it accordingly.

**Comment by namilus** [comment]
Thanks for the suggestions. I've merged them in now so I'll close this issue for now
