### ISSUE TITLE
Submit package to GNU ELPA?

### ISSUE THREAD

**Issue by movedtocodeberg** [namilus/denote-menu#3]
Hi - great package. I'm finding it very useful

Was wondering if you have plans to submit this to GNU ELPA? As that is where `denote` resides

Thanks!

**Comment by namilus** [comment]
Hi @gksudolol ! I'm glad you're finding it useful. Submitting it to GNU ELPA is definitely the plan that I have. I first need to figure out how to actually do that! So hopefully in the next couple days I'll post an update here on the progress.

Also if you have any points of feedback or improvement I'd be happy to hear them, or you can submit a pull request.

Thanks again!

**Comment by protesilaos** [comment]
Hello @namilus!

> I first need to figure out how to actually do that!

You will need to assign copyright to the Free Software Foundation.  A form is available in the Denote manual under the "contributing" heading: https://protesilaos.com/emacs/denote#h:1ebe4865-c001-4747-a6f2-0fe45aad71cd

Once you do that, you need to edit the `elpa-packages` from the elpa.git repository: https://git.savannah.gnu.org/cgit/emacs/elpa.git.  See Denote's own package recipe for an idea.

Commit your changes and prepare a patch.  Then send it to the <emacs-devel@gnu.org> mailing list.  Someone will install it for you.  That "someone" can be me, though it is better for you long-term to go through this process.

**Comment by namilus** [comment]
Hi @protesilaos,

I've sent the form you linked for assigning copyright to the fsf as well as the pdf they sent me back in reply. I've sent an email containing a patch to the elpa repository to include my package. I'll keep this issue open until denote-menu is available to install from elpa. In the meantime we wait (with eager anticipation!)

**Comment by namilus** [comment]
denote-menu is finally on ELPA ! 🥳 🥳
