### ISSUE TITLE
Forked denote-menu added feature, allow user to interactively change the value of denote-directory, e.g silos

### ISSUE THREAD

**Issue by aa-parky** [namilus/denote-menu#4]
First, thank you for a really useful package.

I am not a programmer, rather a happy hacker. So likely better ways to achieve this result.

I forked your repo and have added a function that interactively allow a user to set the denote-directory which is helpful if you use denote's Silos abilities.

Honestly I am not sure if it better placed in denote, denote-menu or just its own little package.

Am happy to submit a pull request, or feel free to look copy etc.

Thanks again.

**Comment by protesilaos** [comment]
Hello @aa-parky!

> Honestly I am not sure if it better placed in denote, denote-menu or just its own little package.

I will let you decide that.  Maybe we can discuss it on the Denote mailing list?  https://lists.sr.ht/~protesilaos/denote/

Note that I also added the _"Use custom commands to select a silo"_ section to the Denote manual: https://protesilaos.com/emacs/denote#h:0f72e6ea-97f0-42e1-8fd4-0684af0422e0

**Comment by namilus** [comment]
Hi @aa-parky 

Apologies for the long delay. I think this is best kept separate, outside of denote-menu. Choosing the silo can be as simple as setting the `denote-directory' variable before calling `list-denotes'. This can be done using a function as part of your emacs config (using the examples prot has linked above) .
