### ISSUE TITLE
denote-menu-filter is not interactive

### ISSUE THREAD

**Issue by heikkil** [namilus/denote-menu#5]
The denote-menu-filter function can not be called interactively. Also, it seems to lack a way to input the regex to filter. Otherwise, the package seems to do what the README says. Thanks!

**Comment by namilus** [comment]
Hello @heikkil,
Apologies for the delay,

You're right. The commit that was pushed onto ELPA had that bug present. I'm preparing a new version to fix and another bug

**Comment by namilus** [comment]
Just pushed the bug fixes. Will prepare a new ELPA release soon
