### ISSUE TITLE
filtering exits with an error

### ISSUE THREAD

**Issue by j4kub5** [namilus/denote-menu#7]
Running `denote-menu-filter` and `denote-menu-filter-by-keyword` returns an error: 

`denote-menu-get-path-by-id: Symbol’s function definition is void: seq-positions`

My config, if needed for reproducing the error: https://github.com/Jack8472/lemacs

**Comment by namilus** [comment]
Thanks for spotting this! What version of emacs are you running? It looks like `seq-positions' was only introduced in emacs 29. I'll rewrite the function so it is compatible with at least emacs 28.1

**Comment by j4kub5** [comment]
I use emacs 28.2 (on archlinux) and 28.1 (on windows).

**Comment by namilus** [comment]
In the most recent commit (210396d), I've removed the call to `seq-positions` and re-implemented `denote-menu-get-path-by-id` using functions that should be available in emacs 28.1. That should fix things

**Comment by j4kub5** [comment]
I confirm. Update by quelpa-upgrade fixed the issue. Thank you very much!
