### ISSUE TITLE
feat request: Add one column display denote signature

### ISSUE THREAD

**Issue by Jousimies** [namilus/denote-menu#8]
Now denote had merged signature branch to main, current denote menu can only show Date, Title and Keywords.

Can add one column to display signature ?

**Comment by EFLS** [comment]
I've added some code to do display such a column in my personal branch of denote-menu. I'll attach the code changes as a patch.

I'm not sure how to turn this into an option one could toggle on and off, as I'm not familiar enough with `tabulated-list-mode`.

[0001-add-signature-to-tabulated-view.patch](https://github.com/namilus/denote-menu/files/11086942/0001-add-signature-to-tabulated-view.patch)

**Comment by namilus** [comment]
Hi @Jousimies @EFLS,

Thank you for your patch. I'll take a look at it in the coming days and edit it to allow for a custom user option to toggle the column

**Comment by Jousimies** [comment]
@EFLS Thank you for your patch, it worked.

The problem is when use regexp to filter some candidate, it runs very slowly. No sure, what caused this problem, I will try to explore it.

**Comment by anthrolisp** [comment]
This would be incredible to include. In the meantime, how to add this manually to the init file? Thank you in advance!

**Comment by namilus** [comment]
Hello everyone @anthrolisp @Jousimies @EFLS ,

Sorry for the late development. I have added the feature for an optional column to include denote file signatures.

Please try out the most recent changes and see if everything is working correctly.

In the meantime I will prepare an update for ELPA to include the new feature.

Thank you.
